version: '3.8'

services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app/result_build/
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_value:/app/static_files/
      - media_value:/app/media_files/


  web:
    image: gutolin/foodgram:latest
    restart: always
    volumes:
      - static_value:/app/static_files/
      - media_value:/app/media_files/
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db_value:
  static_value:
  media_value:
